name: CryWeather
main: me.crylonz.CryWeather
version: 1.5
description: Manage the time
author: Crylonz
commands:
  cday:
    description: Enable day
    usage: /cday [World]
    permission: cryweather.day
  cnight:
    description: Enable night
    usage: /cnight [World]
    permission: cryweather.night
  cmorning:
    description: Enable morning
    usage: /cmorning [World]
    permission: cryweather.morning
  cevening:
    description: Enable evening  
    usage: /cevening [World]
    permission: cryweather.evening
  cafternoon:
    description: Enable afternoon
    usage: /cafternoon [World]
    permission: cryweather.afternoon
  csun:
    description: Enable sun
    usage: /csun [World] [Duration]
    permission: cryweather.sun
  crain:
    description: Enable rain  
    usage: /crain [World] [Duration]
    permission: cryweather.rain
  chelp:
    description: Enable help
    usage: /chelp
    permission: cryweather.help
  cset:
    description: configure time  
    usage: /cset [Time]
    permission: cryweather.set
  cweather:
    description: show version of the plugin
    usage: /cweather
    permission: cryweather.cryweather
  wcday:
    description: Enable day in the current world
    usage: /wcday
    permission: cryweather.wcday
  wcnight:
    description: Enable night in the current world
    usage: /wcnight
    permission: cryweather.wcnight
  wcrain:
    description: Enable rain in the current world
    usage: /wcrain
    permission: cryweather.wcrain
  wcsun:
    description: Enable sun in the current world
    usage: /wcsun
    permission: cryweather.wcsun
  cenablerain:
    description: Allow rain in the server
    usage: /cenablerain
    permission: cryweather.enablerain
  cdisablerain:
    description: Disable rain in the server
    usage: /cdisablerain
    permission: cryweather.disablerain
permissions:
    cryweather.*:
        description: Gives access to all cryweather commands
        children:
            cryweather.day: true
            cryweather.night: true
            cryweather.morning: true
            cryweather.afternoon: true
            cryweather.evening: true
            cryweather.sun: true
            cryweather.rain: true
            cryweather.help: true
            cryweather.set: true
            cryweather.cryweather: true
            cryweather.wcsun: true
            cryweather.wcnight: true
            cryweather.wcrain: true
            cryweather.wcsun: true
            cryweather.cenablerain: true
            cryweather.cdisablerain: true
    cryweather.day:
        description: Allows you to enable day
        default: op
    cryweather.night:
        description: Allows you to enable night
        default: op
    cryweather.morning:
        description: Allows you to enable morning
        default: op
    cryweather.afternoon:
        description: Allows you to enable afternoon
        default: op
    cryweather.evening:
        description: Allows you to enable evening
        default: op
    cryweather.sun:
        description: Allows you to enable sun
        default: op
    cryweather.rain:
        description: Allows you to enable rain
        default: op
    cryweather.help:
        description: Allows you to enable help
        default: op
    cryweather.set:
        description: Allows you to change time
        default: op
    cryweather.weather:
        description: Allows you to view version
        default: op
    cryweather.wcday:
        description: Allows you to enable day in the current world
        default: op
    cryweather.wcnight:
        description: Allows you to enable night in the current world
        default: op
    cryweather.wcrain:
        description: Allows you to enable rain in the current world
        default: op
    cryweather.wcsun:
        description: Allows you to enable sun in the current world
        default: op
    cryweather.enablerain:
        description: Allows you to enable rain on the server
        default: op
    cryweather.disablerain:
        description: Allows you to disable rain on the server
        default: op